### ISSUE TITLE
No items populated in device dropdown

### ISSUE THREAD

**Issue by creativedamages** [sorskoot/StreamDeck-Midi-plugin#1]
When I try to assign a button to midi, I can title it, set the channel and note, but there is no drop down for choosing a midi device. Windows 10.
![image0](https://user-images.githubusercontent.com/46900906/59720354-9fc04c80-91ec-11e9-96dc-6da04b549f82.jpeg)

**Comment by sorskoot** [comment]
I haven't been able to reproduce the issue. 

Would you mind having a look at the log files to see if there's an error in there? You can find the log files at %appdata%\Elgato\StreamDeck\logs on your machine.

**Comment by Cloudgasm** [comment]
Having same issue. Cant select any devices. Log attached 
[StreamDeck0.log](https://github.com/sorskoot/StreamDeck-Midi-plugin/files/3584781/StreamDeck0.log)

**Comment by sorskoot** [comment]
I have been looking into this issue because I really want to get it fixed. The problem is that I'm using the RTMidi.Core library to get the MIDI devices.  I'm showing whatever that library returns as the list of available devices. I'm going to find another way of getting the list of devices, or maybe even switch to another library. StreamDeck needs a _working_ MIDI extension.

**Comment by Jacquesmk2** [comment]
Same issue here, Win10 and no listed devices.

**Comment by Jacquesmk2** [comment]
Hello Timmy, first of all thanks for your work. I tested the new upload, now a list of midi devices appear, however no incoming midi signal yet (tested with Bome/studio one/win10).
Regards

**Comment by sorskoot** [comment]
Thank you very much for letting me know! I might be onto something here and maybe getting this fixed.

**Comment by sorskoot** [comment]
I just created a new release (1.1) that should fix the empty list issue.

**Comment by sorskoot** [comment]
Got feedback that the issue is solved.
